app = 'sample-app'
primary_region = 'nrt'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'fly.Dockerfile'

[[services]]
  protocol = ''
  internal_port = 8000
  processes = ['app']

[[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
